"""Deterministic read-only repository mapping for Lil Tweak."""

from .contracts import (
    AnalysisStatus,
    ComponentNeighborhood,
    EdgeKind,
    EvidenceClass,
    Finding,
    GraphEdge,
    GraphNode,
    ImpactReference,
    ImpactReport,
    MapBinding,
    MapperLimits,
    MappingLimitError,
    NodeKind,
    RepositoryMap,
    RepositoryMapperError,
    RepositoryMutationError,
    RepositorySafetyError,
    SourceBindingError,
    SourceLocation,
    UnknownMapError,
    UnknownNodeError,
)
from .mapper import RepositoryMapService, RepositoryMapper
from .serialization import canonical_json, compute_map_digest, verify_map_digest

__all__ = [
    "AnalysisStatus",
    "ComponentNeighborhood",
    "EdgeKind",
    "EvidenceClass",
    "Finding",
    "GraphEdge",
    "GraphNode",
    "ImpactReference",
    "ImpactReport",
    "MapBinding",
    "MapperLimits",
    "MappingLimitError",
    "NodeKind",
    "RepositoryMap",
    "RepositoryMapService",
    "RepositoryMapper",
    "RepositoryMapperError",
    "RepositoryMutationError",
    "RepositorySafetyError",
    "SourceBindingError",
    "SourceLocation",
    "UnknownMapError",
    "UnknownNodeError",
    "canonical_json",
    "compute_map_digest",
    "verify_map_digest",
]
