export const WORKBENCH_CONTEXT_TOKEN_CAPACITY = 144_000;
export const WORKBENCH_MAX_OUTPUT_TOKENS = 25_772;
export const WORKBENCH_CONTEXT_TOKEN_LABEL = "144k";
export const WORKBENCH_OUTPUT_TOKEN_LABEL = "25,772";
export const WORKBENCH_CAPACITY_LABEL = `${WORKBENCH_CONTEXT_TOKEN_LABEL} / ${WORKBENCH_OUTPUT_TOKEN_LABEL}`;

// The request guard is byte/character based; OpenAI still enforces exact model tokenization.
export const WORKBENCH_MAX_CONVERSATION_CHARACTERS =
  WORKBENCH_CONTEXT_TOKEN_CAPACITY * 4;
export const WORKBENCH_MAX_CHAT_JSON_BYTES = 768 * 1024;
