from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import os
import re
import sys
import uuid
from pathlib import Path
from typing import TextIO

APP_ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(APP_ROOT))

from liltweak.reasoning_contract import ReasoningRole  # noqa: E402
from liltweak.reasoning_evaluation import (  # noqa: E402
    EVALUATION_CONTRACT_DIGEST,
    HOLDOUT_QUALIFICATION_INSTRUCTIONS,
    HoldoutBatchResult,
    HoldoutSuite,
    build_holdout_request,
    canonical_digest,
    evaluate_holdout,
    render_holdout_input,
)
from liltweak.reasoning_policy import ReasoningProfileName  # noqa: E402
from liltweak.reasoning_provider import (  # noqa: E402
    OpenAIResponsesReasoningProvider,
    ReasoningProviderError,
)


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(
        description="Run the frozen, tool-free Lil Tweak Sol reasoning holdout."
    )
    result.add_argument(
        "--suite",
        type=Path,
        default=Path(__file__).parents[1] / "evals" / "reasoning_holdout.json",
    )
    result.add_argument(
        "--profile",
        choices=(ReasoningProfileName.ORDINARY.value,),
        default=ReasoningProfileName.ORDINARY.value,
    )
    result.add_argument("--input-ceiling", type=int, default=8_000)
    result.add_argument("--output-ceiling", type=int, default=4_096)
    result.add_argument("--timeout", type=float, default=240)
    result.add_argument(
        "--run-id",
        default=f"first-label-blind-{uuid.uuid4().hex}",
        help="Unique opaque attempt ID; generated by default.",
    )
    result.add_argument(
        "--evidence-output",
        type=Path,
        required=True,
        help="New, exclusive path for the durable one-shot evidence envelope.",
    )
    return result


def _persist(stream: TextIO, envelope: dict[str, object]) -> None:
    stream.seek(0)
    stream.truncate()
    json.dump(envelope, stream, indent=2, sort_keys=True)
    stream.write("\n")
    stream.flush()
    os.fsync(stream.fileno())


async def run(arguments: argparse.Namespace) -> int:
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._:-]{0,79}", arguments.run_id):
        raise ValueError("run ID must be an opaque safe identifier of at most 80 characters")
    suite = HoldoutSuite.model_validate_json(arguments.suite.read_text(encoding="utf-8"))
    request = build_holdout_request(suite)
    rendered_input = render_holdout_input(suite)
    input_digest = hashlib.sha256(rendered_input.encode("utf-8")).hexdigest()
    common: dict[str, object] = {
        "schema_version": "reasoning-holdout-run-v2",
        "run_id": arguments.run_id,
        "attempt_policy": {"provider_calls": 1, "retries": 0},
        "source_suite_digest": canonical_digest(suite),
        "request_digest": canonical_digest(request),
        "evaluation_contract_digest": EVALUATION_CONTRACT_DIGEST,
        "provider_input_digest": input_digest,
    }
    try:
        descriptor = os.open(
            arguments.evidence_output,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL,
            0o600,
        )
    except OSError:
        print(
            json.dumps(
                {
                    **common,
                    "status": "FAILED_CLOSED",
                    "failure_kind": "evidence_destination_unavailable",
                },
                sort_keys=True,
            )
        )
        return 3

    with os.fdopen(descriptor, "w", encoding="utf-8") as evidence_stream:
        _persist(evidence_stream, {**common, "status": "STARTED"})
        try:
            provider = OpenAIResponsesReasoningProvider(maximum_concurrency=1)
            result = await provider.call(
                call_id=f"qualification:reasoning-holdout-v2:{arguments.run_id}",
                role=ReasoningRole.ANALYST,
                profile_name=ReasoningProfileName(arguments.profile),
                instructions=HOLDOUT_QUALIFICATION_INSTRUCTIONS,
                input_text=rendered_input,
                output_type=HoldoutBatchResult,
                input_token_ceiling=arguments.input_ceiling,
                output_token_ceiling=arguments.output_ceiling,
                timeout_seconds=arguments.timeout,
                qualification_call=True,
            )
        except ReasoningProviderError as exc:
            envelope = {
                **common,
                "status": "FAILED_CLOSED",
                "failure_kind": exc.kind.value,
                "billable_usage": {
                    "input_tokens": exc.input_tokens,
                    "output_tokens": exc.output_tokens,
                    "response_id_digest": exc.response_id_digest,
                },
            }
            _persist(evidence_stream, envelope)
            print(json.dumps(envelope, sort_keys=True))
            return 2
        if result.evidence.input_digest != input_digest:
            envelope = {
                **common,
                "status": "FAILED_CLOSED",
                "failure_kind": "provider_input_binding",
            }
            _persist(evidence_stream, envelope)
            print(json.dumps(envelope, sort_keys=True))
            return 2
        report = evaluate_holdout(suite, result.output, result.evidence)  # type: ignore[arg-type]
        envelope = {
            **common,
            "status": "PASSED" if report.passed else "FAILED_CLOSED",
            "report": report.model_dump(mode="json"),
        }
        _persist(evidence_stream, envelope)
        print(json.dumps(envelope, indent=2, sort_keys=True))
        return 0 if report.passed else 1


def main() -> int:
    return asyncio.run(run(parser().parse_args()))


if __name__ == "__main__":
    raise SystemExit(main())
