[Service]
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=read-only
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectControlGroups=true
RestrictSUIDSGID=true
LockPersonality=true
MemorySwapMax=0
MemoryDenyWriteExecute=true
RestrictRealtime=true
RemoveIPC=true
SystemCallArchitectures=native
UMask=0077
ReadWritePaths=-/var/lib/lil-tweak/.local/share/containers
ReadWritePaths=-/run/user/%U/containers
ReadWritePaths=-/run/user/%U/podman
